name: "Publish PowerShell Module"
description: ""

inputs:
  path:
    description: "Path"
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Publish PowerShell Module ${{ inputs.path }}
      shell: pwsh
      env:
        INPUT_PATH: ${{ inputs.path }}
        GH_REPO_OWNER: ${{ github.repository_owner }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $registerParams = @{
            Name = 'GitHub'
            Uri  = 'https://nuget.pkg.github.com/{0}/index.json' -f $Env:GH_REPO_OWNER
        }

        Register-PSResourceRepository @registerParams

        $pat = ConvertTo-SecureString -String $Env:GH_TOKEN -AsPlainText -Force
        $cred = [System.Management.Automation.PSCredential]::new($Env:GH_REPO_OWNER, $pat)

        $publishParams = @{
            Path       = $Env:INPUT_PATH
            Repository = 'GitHub'
            Credential = $cred
        }

        Publish-PSResource @publishParams
