name: Publish Acr Module
run-name: Publish Acr Module

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - src/Acr/**

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  module:
    uses: ./.github/workflows/module-template.yaml
    with:
      path: src/Acr
    secrets: inherit
