name: Markdown Module

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - src/Markdown/**

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  module:
    uses: ./.github/workflows/module-template.yaml
    with:
      path: src/Markdown
    secrets: inherit
