on:
  workflow_call:
    inputs:
      modulePath:
        required: true
        type: string

jobs:
  publish-module:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/templates/pwsh-publish/action.yaml
        with:
          modulePath: ${{ inputs.modulePath }}
